#!/bin/bash
# testing if you can read a file

pwfile=/etc/shadow

# test file exists and is a file
if [ -f $pwfile ]
then 
    if [ -r $pwfile ]
    then 
        tail $pwfile 
    else    
        echo "Sorry, I am unable to read the $pwfile file"
    fi
else

    echo "Sorry, the file $pwfile does not exist"    
fi
