#!/bin/bash

#iterate through all the files in a directory

for file in /home/Dhaval/Study/Shell/second_lesson/*  /home/Dhaval/Study/*
do 
    if [ -d "$file" ]
    then
        echo "$file is a directory"
    elif [ -f "$file" ]
    then
        echo "$file is a file"
    fi
done
        
